### ISSUE TITLE
getting commit list into step powershell code.

### ISSUE THREAD

**Issue by dmeagor** [OctopusDeploy/Library#1178]
I'm trying to improve the sentry-release-tracking-token-auth plugin to send commit history to sentry.

I've added the build information step to TeamCity but I'm struggling to get either the VcsCommitNumber or the commit array from the powershell step code.

Looking at the system variable docs it states that these variables are only available in the release notes.  Is there a way of doing this without bodging it into the release notes and then parsing it out again?

**Comment by harrisonmeister** [comment]
Hi @dmeagor,

You're right that the documentation on the system variable page is correct. The `Octopus.Release.Package` and associated variables are only available when populating the release notes.

If you want to access these details in a step template, then the variables you need are the [Deployment changes](https://octopus.com/docs/projects/variables/system-variables#deployment-changes) ones instead. These are available in the deployment :)

All of the build information can be accessed via the `Octopus.Deployment.Changes` variable.

Please consider a few things with these variables:

- This variable rolls up changes from multiple releases. For example, imagine release `0.0.1` has been deployed to Dev and Test. Then 3 more releases (`0.0.2`, `0.0.3`, and `0.0.4`) are created and deployed to **Dev only**. When the release `0.0.4` gets deployed to Test, the variable can contain multiple entries for build information for packages (build info for releases `0.0.2`, `0.0.3`, and `0.0.4` respectively). This is because the Test environment hasn't had the changes deployed to it previously. See [this](https://octopus.com/docs/releases/deployment-notes) for more details.
- Pre-release versions are handled differently from normal versions, and you may not see any build information for such releases when using these variables. See [this](https://octopus.com/docs/releases/deployment-notes#Versioning) for more details.
- Since the variable is a collection of changes, you'll want to decide on an appropriate strategy of either:
  - selecting all commits - some of which may be duplicated across releases, so would need de-duping, or 
  - choosing the first commit for a package - there could also be multiple packages. 

I hope that helps!
