### ISSUE TITLE
The service cannot accept control messages at this time

### ISSUE THREAD

**Issue by herlusicarus** [OctopusDeploy/Library#1374]
### Step template
IIS AppPool - Start

### Step template parameter inputs
Application Pool Name

### Step template version
Version 4

### Step template related environment information
Internet Information Services

### Octopus Server version
v2022.4 Build 8369

### Expected behavior

Start an application pool

### Actual behavior

Randomly fails to start the application pool with an error "The service cannot accept control messages at this time"

### Possible solution
Usually the command will work on retry. Atleast a retry after 30s can be part of the step.

### Steps to reproduce the problem (for bugs)
Can be reproduced randomly, when the step is used in a build process.

**Comment by IsaacCalligeros95** [comment]
Hey @herlusicarus, as of 2023.2 we've released auto-retries to steps that should handle the behaviour requested here and is generic and available in all steps a few exceptions. There's more details over on [octopus.com/blog](https://octopus.com/blog/step-retries#:~:text=Octopus%202023.2%20introduces%20Step%20Retries,or%20transient%20errors%20during%20deployment.). I know this is a bit ahead of your current version but rather than implementing specific functionality for this step we'd instead use that shared behaviour which we'll continue to build on in the future. I'll leave this issue open for now in case you have any queries or feedback, but hopefully, this resolves your issue.
