### ISSUE TITLE
IIS-AppPool Create Step Template doesn't cover all Runtime Options

### ISSUE THREAD

**Issue by seamustheseagull** [OctopusDeploy/Library#302]
Great library. I ran into an issue when I needed to create a new Application Pool that specifically didn't use a .NET CLR, instead using the "No managed code" option.

The correct way to set this in the library is to just set the ManagedRuntimVersion to an empty string. So I modified the step template on my own Octopus server and added in an option;

**None|No Managed Code**

And then in the relevant section of the script;

```
    IF ($appPoolManagedRuntimeVersion -ne "None")
    {
        Write-Output "Setting: ManagedRuntimeVersion = $appPoolManagedRuntimeVersion"
        $pool.ManagedRuntimeVersion = $appPoolManagedRuntimeVersion
    }
    else 
    {
        Write-Output "Setting: ManagedRuntimeVersion = None"
        $pool.ManagedRuntimeVersion = ""
    }
```

Not entirely sure how to push changes to public repos on GitHub, so posting it here.

**Comment by alfhenrik** [comment]
Hi @seamustheseagull!

Thanks for reporting this issue, GitHub has an excellent [article](https://help.github.com/articles/using-pull-requests/) on how to send pull requests to public repositories. Let me know if you'd like to give it a go, otherwise, I can update the step template and push it for you.

Thank you and warm regards,
Henrik

**Comment by alfhenrik** [comment]
This has been implemented
