### ISSUE TITLE
"Cutomized Cloud servicce Step template" needed for working with Deployment target machines

### ISSUE THREAD

**Issue by nitin-natu** [OctopusDeploy/Library#367]
Hi we working on Cloud and AWS projects leveraging octopus extensively for our Deployments.
## Problem Statement :

We are working with new octopus online 3.x server for doing Cloud service deployments with Cloud Service deployment step.

Our Predeploy and Deploy scripts in cloud package are getting executed on Octopus server instead of Deployment targets machines added for Cloud service Environments  or Octopus Tentacles.

As octopus Server don't have Azure SDKs and required Dlls we cant perform certain unpack and packing operations on Cloud packages which we were doing previously with Internal octopus Servers with Azure deployment machines as octopus tentacles to perform this activities.
## Our Requirements :

we need predeploy and deploy script extensively for updating csdef files for VM user name , password and certificates as octopus steps can transform only appsettings and Connections for Azure service and storage table by default and  **## for following  important tasks** ..

**## We need to predeploy scripts :** 
1. Unzip nuget package first for cloud cspack file.
2. unpack cloud package (cspack) , copy worker role inside cloud package on some folder location on Deployment machine , create 4 worker roles at runtime .
## **Deploy script Usage**
1. to pack this four worker roles in one cloud package before we actually deploy cloud package to Cloud service. this can be only done with having deployment target machines on octopus tentacles as it has Azure SDKs and libraries to pack the Cloud package again .
   Current online octopus server don't have any Azure SDKs and required binaries.

Please suggest something on this for usage of customized templates.

**Comment by Damovisa** [comment]
Hi @nitin-natu,

It sounds like what you need is already provided by the [Azure Cloud Service step](http://docs.octopusdeploy.com/display/OD/Deploying+a+package+to+an+Azure+Cloud+Service). It operates much the same way as before, but it does everything on the Octopus Server instead of requiring a tentacle.

You can see the exact steps that are performed in [the Azure Cloud Service step documentation](http://docs.octopusdeploy.com/display/OD/Deploying+a+package+to+an+Azure+Cloud+Service#DeployingapackagetoanAzureCloudService-Deploymentprocess), but to achieve what you want you can include a `Deploy.ps1` (or `PreDeploy.ps1` depending on when you want to run the script) that performs those tasks.

As for the Azure SDK being installed, the Octopus Server already comes bundled with the Azure SDK. If you need a different version than the one that comes bundled, [you can configure it with these instructions](http://docs.octopusdeploy.com/display/OD/Configuring+the+version+of+the+Azure+PowerShell+modules).

If you need any additional tools or libraries, they'll need to be installed on the Octopus Server.

**Comment by nitin-natu** [comment]
We are using Predeploy and deploy scripts , issue we are facing is  in old octopus way our nugget package containing cloud package cspkg and config files was auto extracted before we work on predeploy script to extract further cspack file and its contents..

How can we unzip the main nugget package (contains csppack and config files) before predeploy step starts ?

**Comment by Damovisa** [comment]
Hi @nitin-natu,

What you've described is exactly what should be happening. The nuget package and the cspkg should be extracted before the predeploy script runs. See steps 2 to 4 in bold from the documentation (link in the previous message):

1. Download the package from the package repository
2. **Extract the package on the Octopus server to a temporary location**
3. **Extract the Cloud Service package (.cspkg) to a temporary location**
4. **Any configured or packaged PreDeploy scripts are executed**
5. Variable substitutions in Cloud Service configuration file (.cscfg)
6. Substitute variables in files (if configured)
7. XML configuration transformations (if configured) are performed
8. XML configuration variables (if configured) are replaced
9. Any configured or package Deploy scripts are executed
10. Re-package the Cloud Service Package
11. Upload the Cloud Service Package to Azure Storage
12. Deploy the Cloud Service Package (see 'Customizing the deployment process' section below)
13. Any configured or packaged PostDeploy scripts are executed

Is this not happening?

**Comment by alfhenrik** [comment]
Hi @nitin-natu, 

As we haven't heard back from you I'm going to close this issue for now. If you are still experiencing issues with your cloud service deployments, please let us know and we'll re-open this issue and we'll do our best to help you get to the bottom of your issue.

Thank you and best regards,
Henrik
