### ISSUE TITLE
run-entity-framework-migrations requires bin-folder, doesn't work for running migrations on Windows Service projects

### ISSUE THREAD

**Issue by andreasnilsen** [OctopusDeploy/Library#577]
It seems the step template is hard coded to expect a bin-folder with the EF-assemblies, and a web.config file.
This is fine for ASP.NET-applications, but for OctoPack-packaged Windows Services, these will reside in the root folder with the rest of the application, and it will have a <servicename.dll.config> file instead.

It would be nice if this was configurable in the step template.

**Comment by alfhenrik** [comment]
@andreasnilsen thanks for getting in touch! Would you be interested in sending a [Pull Request](https://help.github.com/articles/creating-a-pull-request/#changing-the-branch-range-and-destination-repository) to fix the step template so that you can specify the output path to copy the `migrations.exe` file? If not, that's OK and I'll have a look as soon as I can.

Thanks,
Henrik

**Comment by andreasnilsen** [comment]
Thanks, I'm sure these changes will work but after upgrading the step template a previous change in https://github.com/OctopusDeploy/Library/commit/9e23a8de6d0900ddb61a0546950615e1ed826959 to this template makes it incompatible with my setup 
, as I ship a copy of migrate.exe within the nuget package containing the EF-context assembly to make it self-contained, thus the script tries to copy it from and to the same folder, failing.

As far as I can see, the step template will fail if the source folder of migrate.exe == base directory.

I guess a quick workaround is to just move migrate.exe to its own folder.

Btw in the help text for Site Path, "/bin" should probably be changed to "Base Directory".
