### ISSUE TITLE
Dacpac can't extract if the database doesn't exist.  Chicken and Egg...

### ISSUE THREAD

**Issue by kmramsey** [OctopusDeploy/Library#607]
### Steps to reproduce the problem (for bugs)
1. Try to create a database with a dacpac and select all of the check boxes in the step template.  Report/Script/Extract target database to dacpac.

The step fails because the database doesn't exist yet.

**Comment by gdovicak** [comment]
I have experienced this same issue. For an initial deploy I have to set Script, Report, and Extract target database to false. Once that deploys successfully, then I turn on the values that I want.

Having to do this becomes a bit painful, especially if it has been a while since this error was encountered and the issue has to be tracked down all over again

I am hoping to get some time to submit a PR for this issue.

**Comment by DevOpsDerek** [comment]
Closing as no comment in 3 years.
