### ISSUE TITLE
Step Template peer review step is stupid

### ISSUE THREAD

**Issue by jzabroski** [OctopusDeploy/Library#826]
I just submitted a pull request for #822 and the automatically generated comment is annoying because it demonstrates a lack of understanding on how to build PowerShell scripts.

I think the following simplification of the PR for #822 should demonstrate why this peer review step is effectively irrelevant, but will require fixing 300-something Step Templates to use this Immediately Invoked Script Block design pattern:

```powershell
# Running outside octopus
param(
    [string]$MsiFilePath,
	[ValidateSet("Install", "Repair", "Remove", IgnoreCase=$true)]
	[string]$Action,
	[string]$ActionModifier,
    [string]$LoggingOptions = "*",
    [ValidateSet("False", "True")]
    [string]$LogAsArtifact,
	[string]$Properties,
	[int[]]$IgnoredErrorCodes,
    [switch]$WhatIf
) 

$ErrorActionPreference = "Stop"

function Dump-Params
{
    Write-Host " MsiFilePath: $MsiFilePath" -f Gray
	Write-Host " Action: $Action" -f Gray
	Write-Host " ActionModifier: $ActionModifier" -f Gray
	Write-Host " LoggingOptions: $LoggingOptions" -f Gray
	Write-Host " LogAsArtifact: $LogAsArtifact" -f Gray
	Write-Host " Properties: $Properties" -f Gray
	Write-Host " IgnoredErrorCodes: $IgnoredErrorCodes" -f Gray
}

function Get-Param($Name, [switch]$Required, $Default) {
    $result = $null

    if ($OctopusParameters -ne $null) {
        $result = $OctopusParameters[$Name]
    }

    if ($result -eq $null) {
        $variable = Get-Variable $Name -EA SilentlyContinue   
        if ($variable -ne $null) {
            $result = $variable.Value
        }
    }

    if ($result -eq $null) {
        if ($Required) {
            throw "Missing parameter value $Name"
        } else {
            $result = $Default
        }
    }

    return $result
}

Write-Host "Dumping params outside of IIFE: "
Dump-Params

& {
    param(
        [string]$MsiFilePath,
		[string]$Action,
		[string]$ActionModifier,
        [string]$LoggingOptions,
        [bool]$LogAsArtifact,
		[string]$Properties,
		[int[]]$IgnoredErrorCodes
    ) 

	Write-Host "Dumping params inside of IIFE: "
	Dump-Params
	
} `
(Get-Param 'MsiFilePath' -Required) `
(Get-Param 'Action' -Required) `
(Get-Param 'ActionModifier') `
(Get-Param 'LoggingOptions') `
((Get-Param 'LogAsArtifact') -eq "True") `
(Get-Param 'Properties') `
(Get-Param 'IgnoredErrorCodes')

Write-Host "Dumping params after IIFE"
Dump-Params
```
You can save the above script to a file, `Test-PsImmediatelyInvokedScriptBlock.ps` and call it on the command line and see my point:

```powershell
PS D:\source\OctopusDeploy\Library> .\Test-PsImmediatelyInvokedScriptBlock.ps1
Dumping params outside of IISB:
 MsiFilePath:
 Action:
 ActionModifier:
 LoggingOptions: *
 LogAsArtifact:
 Properties:
 IgnoredErrorCodes:
Dumping params inside of IISB:
 MsiFilePath:
 Action:
 ActionModifier:
 LoggingOptions: *
 LogAsArtifact: False
 Properties:
 IgnoredErrorCodes:
Dumping params after IISB
 MsiFilePath:
 Action:
 ActionModifier:
 LoggingOptions: *
 LogAsArtifact:
 Properties:
 IgnoredErrorCodes:
PS D:\source\OctopusDeploy\Library> $LoggingOptions
PS D:\source\OctopusDeploy\Library>
```

**Comment by michaelnoonan** [comment]
Hi @jzabroski.

It took me a while to understand the specific thing you are calling out. I think it's this line in the Pull Request template: https://github.com/OctopusDeploy/Library/commit/8bf651404d34d3cdf3a3d4147b0361517f6ace4d Is that correct?

If I am interpreting your intent correctly, I agree with your sentiment. I prefer to author my Octopus step templates using a similar approach to you: I write a single script which works in my local development environment and in Octopus. There are several benefits to this approach, but it's also just good coding practice.

## Why did we add this tip?

We added the tip to the pull request template after a series of customers "shot themselves in the foot". They authored a poorly encapsulated step template which misbehaved.

## Why did we hand them a gun in the first place?

In hindsight, I wish we took their gun away altogether, forcing all newly created step templates to use a better encapsulation pattern, rather than simply offering a cheat's way out.

## Where to from here?

I'm starting an internal discussion to question the status quo and update our guidance + pull request template.

## What about your pull request?

Press on! That line in the pull request template is just a tip.

Hope that helps!
Mike

**Comment by michaelnoonan** [comment]
Oh no! I think I've missed a nuance here.

Imagine you author a step template with a parameter called `Username`.

Now imagine someone else uses that step template in a project, and in that step, they set the `Username` parameter value to `elephant`.

Now imagine they also have a project variable called `Username` and give it a value `monkey`.

Even though you've authored the step template using the IIFE pattern with strong encapsulation, their process may not work as expected because there are two `Username` values floating around. Octopus chooses which value to use based on the specificity of the value.

I still think there is room for improvement somewhere here, and we are hunting for it while we are thinking this through.

**Comment by michaelnoonan** [comment]
Here is an issue we discovered where the least invasive change was to inform the person deploying the project that there is a problem: https://github.com/OctopusDeploy/Issues/issues/2126

**Comment by droyad** [comment]
I have revised the wording a bit, does that make it clearer? #827

**Comment by jzabroski** [comment]
Execute it in a Runspace.

**Comment by michaelnoonan** [comment]
Hi @jzabroski,

Interesting idea, but I don't think that helps. The problem here is not with PowerShell variable isolation. No matter how strongly a developer encapsulates their PowerShell script, or the runtime environment, the script still needs to ask Octopus for the value of each variable. Unfortunately for all of us, the wires get crossed when asking Octopus for the value of variable where there are duplicates.

Variable management is a core part of Octopus and every deployment process in the world depends on the behaviour being consistent. I hope you can appreciate the care we take when considering changes to the runtime environment of scripts, or the underlying constructs they depend upon.

Hope that helps!
Mike

**Comment by jzabroski** [comment]
I'm pretty skeptical of what you're saying.  I can see why you feel my solution might be hard to prototype, but I recently worked with a PowerShell expert Michael Klement who helped me learn a lot about PowerShell ins and outs.

I understand you're responsible for helping keep the Octopus Deploy ship afloat and enhance value for all customers, and you're probably equally skeptical that by updating 300+ scripts using IIFE/IISB the problem will just go away.  And you have a right to be, since it's a lot of work and the way Octopus Deploy exports scripts with \n makes reviewing the PowerShell piece of step templates simply obnoxiously hard job for you.

What can we do to improve the situation so that you can keep the ship afloat and make the decks cleaner so the Giant Octopus of script unmaintainability doesnt swarm the decks?

**Comment by jzabroski** [comment]
I think you should probably build a lightweight repro of #2126 to explain how the problem crops up.  It sounds like Octopus Deploy basically uses global variables everywhere, and that nobody in 4+ years has had any interest in making things safer.  Sorry, just being blunt here.

I don't know the internals of how OctopusParameters get populated, but there is very clearly a major problem with how this works if it conflates arguments with parameters.

**Comment by jzabroski** [comment]
The more I think about your objections, the more I realize you may not understand how PowerShell works.  (I was in the same boat a few months ago, since some of this is VERY esoteric stuff known to maybe 500 engineers worldwide.)

Let's walk through this:

1. Immediately Invoked Script Block
    - Quasi-isolated, but still allows dynamically scoped variable capture, which could cause some problems if the whole Step Template script is allowed to mutate outer variable's state.
    - Even though not a full solution, it does provide clear guidance on how someone can develop a PowerShell script and easily mock $OctopusParameters.
2. New RunSpace per Step Template
    - Fully isolated environment for PowerShell variables
    - If you load the RunSpace using the PowerShell SDK in C#, you run zero risk that your "PowerShell runner" will go crazy, because you're setting up and tearing down a Step Template in much the same way a unit test is set-up and torn down.
    - You can always implement a `try-finally` to copy the variable stack prior to passing in `$OctopusParameters` to your RunSpace.  Similar to how GUI programmers save the current mouse cursor state prior to doing an operation, and then reverting the mouse cursor state in a finally block, to ensure that even if an exception is thrown, the cursor does not stay stuck in a "busy" affordance.  In this example, `$OctopusParameters` is your mouse cursor.

**Comment by droyad** [comment]
@jzabroski Thank you for the interest in making Octopus a better product. I'll try and clear a few things up. Firstly, every script is started in a brand new process which provides isolation and prevents two scripts from interfering from each other. Additionally once control is handed over to the user provided script, we no longer rely on any state in the script. If you wanted to find out how we do it, [here](https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari/Commands/RunScriptCommand.cs#L55) is a good place to start.

Rest assured we do have a tool that makes reviewing the actual scripts easy.

On to the problem we are trying to avoid. Lets say you define a Template Parameter named `Database` like this:
```
"Parameters": [
    {
      "Id": "381f31f3-2cad-45fa-96ea-d99b2299667c",
      "Name": "Directory",
      "Label": "Directory Name",
      "HelpText": "",
      "DefaultValue": "",
      "DisplaySettings": {
        "Octopus.ControlType": "SingleLineText"
      }
    }
]
```

This means that when the user uses this step template, they get a field labeled `Directory Name` and you can use `$directory` or `$OctopusParameters["Directory"]` in the script to access the user entered value. A key thing to note is that once a step template is added to a process, it is treated like a built in step, including the custom fields.

Lets say the user entered `c:\temp` as the value of the field `Directory Name` (which under the covers is named `Directory`). Lets also say they've defined a project variable named `Directory`, set it to `d:\other` and scoped it to the environment `Production`.

When we prepare the step for execution, we gather all the variables together (`VariableCollection`) from the step (and template), the project, the environment, the target and so on. In our scenario we end up with a list of values  for `Directory` like this:
```
Value           |   Scope
-----------------------
c:\temp        |  "System", "Step"
d:\other       |   "User", "Environment:Production"
```

Since it doesn't make sense to [provide multiple values](https://octopus.com/docs/deployment-process/variables#using-multiple-scopes) for the same variable, we have some [rules](https://octopus.com/docs/deployment-process/variables#Scopingvariables-Scopespecificity) that determine which variable we choose.

In the case above, we would choose `d:\other` as `User` entered variables have higher priority than `System` variables. Values entered in the step are considered `System`. This behaviour can't be changed as many customers rely on it working this way. We have a philosophy of keeping upgrades as frictionless as possible, "Move fast and keep things working".

Once we have boiled each variable name down to a single value (a `VariableDictionary`), we send them over to the target ready to be included in the execution of the step (which may or not involve a PowerShell script). The `VariableDictionary` is discarded after it is sent, and the the above process is repeated for each Step/Target combination from the original `VariableCollection`. The values in `VariableCollection` are never modified (except for well defined variables prefixed with `Octopus.`).

The variable system of Octopus is one of it's most powerful features. However with that power and flexibility comes complexity and it does sometimes interact in ways that are not immediately obvious.

We could have avoided this clash of variables by automatically prefixing Step Template variables with `StepTemplate.`. However this would make it harder to move a normal step it a step template as all the supplied variables would need updating. Also that ship has sailed and changing it now would break almost everyone.

The most pragmatic thing we could do is ask the user to prefix their variables so that collisions are highly unlikely.

We do warn the end user if we detect a collision, so they can rectify it. The easiest way to do this is rename the parameter in the template and update the template script. In the case of steps from the Libary, the end user has little control over it and must change their project variable (and all the places it's used) instead.
